web:
  extends:
    file: docker-compose.common.yml
    service: web
  build: .
  volumes:
    - .:/usr/src/app
postgres:
  image: postgres:9.4.5
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
  ports:
    - "5432"
